### PR TITLE
Added GitHub DevFinder app to React folder

### PR DESCRIPTION
**Pull request by shanolhere**
Please review and merge my PR request. Thanks in advance.

### CODE REVIEW

**Review by codersalman — APPROVED** [review]
Grate work @shanolhere 🚀, So you are a crework member 👀😄

**Comment by shanolhere** [comment]
yes @codersalman. Thanks for accepting my PR request. Btw, the Crework community is amazing.

**Comment by codersalman** [comment]
> yes @codersalman. Thanks for accepting my PR request. Btw, the Crework community is amazing. 


I know, I wanted to be a part of that,

**Comment by codersalman** [comment]
> yes @codersalman. Thanks for accepting my PR request. Btw, the Crework community is amazing. 

Welcome, 🙃 I was just checking your crework projects, you are doing great, don't stop just go ahead 👀💚

**Comment by shanolhere** [comment]
Thank you so much for your kind words @codersalman

**Comment by codersalman** [comment]
> Thank you so much for your kind words @codersalman

My Pleasure💚,  share this repo with your crewmates

**Pull request merged**
