### PR TITLE
Create Pratheeksha_loginpage

### PR DESCRIPTION
**Pull request by 035pratheeksha**
Please look into this and add me as a contributor for hacktoberfest.

### CODE REVIEW

**Comment by 035pratheeksha** [comment]
Why was i not accepted? @codersalman

**Review by codersalman — CHANGES_REQUESTED** [review]
Create direcotry for java and movw project

**Comment by 035pratheeksha** [comment]
> Create direcotry for java and movw project

what does that mean?

**Comment by codersalman** [comment]
> > Create direcotry for java and movw project
> 
> what does that mean?

create folder with java name and move your contibution into that one

**Comment by 035pratheeksha** [comment]
> > > Create direcotry for java and movw project
> > 
> > 
> > what does that mean?
> 
> create folder with java name and move your contibution into that one

Yeah done.
Please look into this and add me as a contributor for hacktoberfest.

**Review by codersalman — APPROVED** [review]

**Comment by 035pratheeksha** [comment]
Thank you soo much for supporting a newbie and giving such opportunities.

**Pull request merged**
