### PR TITLE
Added JavaScript Project

### PR DESCRIPTION
**Pull request by iamrahul8**
# Random Number Generator

Issue solved : #10 

## Technologies used :
- HTML
- CSS
- Js

@codersalman ,Please merge it under `hacktoberfest`

### CODE REVIEW

**Comment by codersalman** [comment]
welcome

**Review by codersalman — CHANGES_REQUESTED** [review]
Add javascript  lable

**Review by codersalman — APPROVED** [review]

**Comment by iamrahul8** [comment]
@codersalman , please add `hacktoberfest-accepted` tag , so that it can be counted as contribution 🙂

**Comment by codersalman** [comment]
> @codersalman , please add `hacktoberfest-accepted` tag , so that it can be counted as contribution 🙂

Yeah

**Pull request merged**
