### PR TITLE
IOT/Arduino

### PR DESCRIPTION
**Pull request by Nipunya1601**
Piano using piezo buzzer and push buttons (Arduino UNO)

### CODE REVIEW

**Review by codersalman — COMMENTED** [review]
Good

**Comment by codersalman** [comment]
Add the Contribution file in ./Arduino Directory

**Review by codersalman — CHANGES_REQUESTED** [review]
Add Files in the Proper Directory

**Review by codersalman — APPROVED** [review]

**Comment by codersalman** [comment]
Thank you for your Contribution - PR 🙃💚 Happy Hacking🛠

**Comment by Nipunya1601** [comment]
> Thank you for your Contribution - PR 🙃💚 Happy Hacking🛠

Thank you!

**Pull request merged**
